### ISSUE TITLE
Align sbt version with Chisel3

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/firrtl#101]
Is there a reason Chisel3 and firrtl use different sbt versions (0.13.7 and 0.13.6, respectively)?

If not, it would be nice for them to match, so that it is faster to get started from a clean install. It takes a long time to download both.

**Comment by aswaterman** [comment]
I'm going to try moving `everything' (chisel, chisel3, firrtl, rocket-chip)
to sbt 0.13.11.

**Comment by jackkoenig** [comment]
There's no reason they don't match. 

I agree with Andrew's solution
