### ISSUE TITLE
Delays are not supported in Verilator

### ISSUE THREAD

**Issue by azidar** [ucb-bar/firrtl#103]
When we initialize registers/memories with random values, we emit `#0.002;` to delay initialization, allowing the random seed to be set by the test harness (at least originally). This construct isn't supported in verilator - perhaps we should just omit it? Or should we figure out another way to set the seed properly? @aswaterman

**Comment by aswaterman** [comment]
I think we still need this for VCS.  Does Verilator just ignore it, or does it issue an error?  Can we guard it with `ifndef VERILATOR or something?

**Comment by aswaterman** [comment]
(it turns out `ifndef verilator, i.e. lower case, does what you'd hope)

**Comment by palmer-dabbelt** [comment]
You can make Verilator ignore them, but I think we should `ifndef VERILATOR so we don't end up silently changing the behavior of other testbench code.

**Comment by azidar** [comment]
Yup, `ifndef verilator works, I'll submit a pull request.
