### ISSUE TITLE
Puzzling FIRRTL error

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/firrtl#105]
Got this FIRRTL error in Travis.

https://travis-ci.org/ucb-bar/rocket-chip/jobs/120801507#L1274

What does this mean, exactly. Is it an internal FIRRTL issue?

**Comment by jackkoenig** [comment]
Yeah match errors should never happen, it's definitely an internal error.
The good news is I'm in the process of revamping that pass, I'll make sure
I fix whatever this is in the process.

**Comment by azidar** [comment]
Yes, it is definitely a FIRRTL bug - can I see the FIRRTL source?

**Comment by jackkoenig** [comment]
@azidar I'm about to PR some major changes to LowerTypes which is where the match error is, so I wouldn't look at this until then.

**Comment by azidar** [comment]
The problem is a WSubAccess has leaked out of the "RemoveAccesses" passes - there shouldn't be anything wrong with the LowerTypes pass (with respect to this error), so it is probably independent of your PR. However, if you'd rather wait, that's fine with me.

**Comment by jackkoenig** [comment]
Oh yeah, you're right. Nevermind, no reason to wait.

**Comment by zhemao** [comment]
If you want to reproduce, checkout the axi-fix branch of RocketChip and try to build with NastiConverterTestConfig.

**Comment by jackkoenig** [comment]
Here's a small example that causes the error:

This FIRRTL file can be compiled and executed as a test
```
circuit NestedIndexTester :                                                                                                                                                                                                                                                   
  module NestedIndex :
    input foo : UInt<1>[4]
    input index : UInt<2>
    output out : UInt<4>

    wire vec : UInt<4>[2]
    vec[0] <= UInt(3)
    vec[1] <= UInt(4)

    out <= vec[foo[index]]

  module NestedIndexTester :
    input clk : Clock
    input reset : UInt<1>

    inst dut of NestedIndex

    dut.foo is invalid
    dut.index <= UInt(2)

    when neq(dut.out, UInt(4)) :
      printf(clk, not(reset), "Assertion failed\nTest Failed!\n")
      stop(clk, not(reset), 1)
    else :
      stop(clk, not(reset), 0)
```

**Comment by jackkoenig** [comment]
I've created a branch that has a test that will fail until this is fixed

https://github.com/ucb-bar/firrtl/tree/fix-remove-subaccess
