### ISSUE TITLE
Strange width inference bug crosses unrelated modules

### ISSUE THREAD

**Issue by aswaterman** [ucb-bar/firrtl#135]
https://gist.github.com/aswaterman/75f8016abf83c0df569273862c4c1bc6

A wire in module A (which is never instantiated) is given the width of a wire in module C (which is also never instantiated).

**Comment by aswaterman** [comment]
Looks like InferTypes is broken, as both wires are given the type UInt<w>

https://gist.github.com/aswaterman/18901a8202c912ef98c4395837a5eeba

**Comment by jackkoenig** [comment]
This is my fault, due to f8e5c736908dadafc3eda30482d13ad37b81b24d

I made separate width namespaces for each module rather than a single global one.
