### ISSUE TITLE
Static Shift by UIntValue amount rather than constant causes IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/firrtl#168]
The following FIRRTL:

```
circuit Test :
  module Test :
    input a : UInt<16>
    output b : UInt
    b <= shr(a, UInt(2))
```

Gives a java.lang.IndexOutOfBoundsException in CInferTypes because it is using a UIntValue (and thus an additional arg) rather than just a constant positive integer. 

Related question:  Is it really that important to distinguish between integer constants and literal expressions in primitive operations? It kind of strikes me as a distinction without a difference, but I'm probably missing something.

**Comment by azidar** [comment]
We want to make sure that the primops are simple for passes, so enforcing the correct type signature is important. Also, this should be fixed with the check chirrtl pass.
