### ISSUE TITLE
reg syntax differs from spec

### ISSUE THREAD

**Issue by gkelly** [ucb-bar/firrtl#197]
The spec shows a `reg` statement as looking something like:

    reg id : type, exp, [exp, exp]?

Where the parser is looking for:

    'reg' id ':' type exp ('with' ':' '{' 'reset' '=>' '(' exp exp ')' '}')?

This was introduced in 676fbd9f97fcbedf351a904b645eb200c12144a5.

**Comment by azidar** [comment]
Thanks, the spec is incorrect, I'll update it.

**Comment by azidar** [comment]
#204

**Comment by nturley** [comment]
This isn't quite complete.

In the Register section, it gives [an example of the reset syntax](https://github.com/ucb-bar/firrtl/blob/cca37c46fc0848f5dbf5f95ba60755ed6d60712b/spec/spec.tex#L483) that is still the old way instead of the new way.
