### ISSUE TITLE
Better Usage message(s) for cmd line args

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/firrtl#234]
Can we add to the FIRRTL README some indication of how to figure out what the FIRRTL cmd line arguments are. 

I believe the correct action is:

$FIRRTL --help

However, this doesn't print out all the arguments.  For example the --inline flag has no explanation, and the new flags introduced on @shunshou's sub_mem_bb don't show up if you use --help. 

Isn't there some way (similar to python's argparse) that can handle the argument parsing and documentation in one pass?

Giving an unknown argument should also print the correct usage in addition to complaining about the unsupported argument.

**Comment by kammoh** [comment]
I can chip in scopt (https://github.com/scopt/scopt) for arg parsing.

**Comment by azidar** [comment]
That would be awesome @kammoh! For now I'll push a fix that updates the usage string and prints it on incorrect args, and then feel free to submit the PR and I'll merge it.

**Comment by kammoh** [comment]
I could probably hack up a PR in a few days if that's cool and the added
dependency is fine.

**Comment by azidar** [comment]
Yeah, the added dependency its fine. Thanks!
