### ISSUE TITLE
Correct clock connections in InferReadWrite.

### ISSUE THREAD

**Issue by donggyukim** [ucb-bar/firrtl#307]
Clocks signals should be correctly connected by examining ports' clocks.
(found in #306)

**Comment by aswaterman** [comment]
Any chance you have a fix yet?

**Comment by donggyukim** [comment]
I'm working on this on top of #306. It should be done soon.

**Comment by aswaterman** [comment]
cool thanks

**Comment by shunshou** [comment]
When you do fix this, you should also prob check what Andrew said in the other issue -- don't do optimization if read/write ports use different clocks. Didn't think about that when I looked through it...
