### ISSUE TITLE
Spec wrong for resultant bits of add

### ISSUE THREAD

**Issue by chick** [ucb-bar/firrtl#308]
Firrtl spec says in section 7.1
```
add(UInt(w1), SInt(w2)) should result in SInt(w1.max(w2)+1)
```
But consider
```3.U<2> + 1.S<2>``` should have the numeric result +4 requiring 3 bits but because the result needs a zero sign bit so 4 can be positive, 
the actual SInt requires 4 bits or ```SInt(w1.max(w2)+1)```.
This is causing the interpreter to blow up.  Should the spec be changed, or if not what should the interpreter do here.

**Comment by aswaterman** [comment]
Largest positive value is 2^w1 + 2^(w2-1) - 2, so max(w1, w2-1)+1+1 should suffice.

Largest negative value is -2^(w2-1), which is already dominated by the previous expression.

**Comment by chick** [comment]
Where w2 is always the width of the SInt for both cases ```SInt + UInt``` and ```UInt + SInt```

**Comment by aswaterman** [comment]
Yeah, that follows from commutativity

**Comment by chick** [comment]
@jackkoenig @azidar, any plan on this?  This issue and #193 are causing users problems in the field when running the interpreter.  I don't think I can fix this in the interpreter without it agreeing with firrlt's behavior in this situation.  I think the fixes are fairly easy, plus an update to the manual
