### ISSUE TITLE
RW-port inference breaks unless there's a signal named "clk"

### ISSUE THREAD

**Issue by aswaterman** [ucb-bar/firrtl#309]
The following bails out in ResolveKinds because the RW-inference pass assumes the clock is named "clk."  It should get the clocks from the ports, rather than hard-coding it (and only perform the optimization if the read and write clocks match).

    circuit foo :
      module foo :
        input clock : Clock
        input cond : UInt<1>

        smem mem : UInt<19>[2][256]

        wire w : UInt
        w is invalid
        when not(cond) :
          w <= UInt(0)

        read mport tag_rdata = mem[w], clock
        when cond :
          write mport T_906 = mem[UInt(0)], clock

**Comment by donggyukim** [comment]
It's duplicate with #307
