### ISSUE TITLE
ASIC rams

### ISSUE THREAD

**Issue by azidar** [ucb-bar/firrtl#31]
Need pass to remove smem's and replace with blackboxes

**Comment by jackkoenig** [comment]
This is super dated, but @albert-magyar has written something for this

**Comment by azidar** [comment]
@albert-magyar, can you make a pull request?

**Comment by albert-magyar** [comment]
I'm changing the pass to allow enables on aggregate memories to be processed down to enable types available in the concrete memories.

**Comment by donggyukim** [comment]
By #265
