### ISSUE TITLE
Specifying defaults for W___ 

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/firrtl#461]
Right now, when we write passes, we either have to use helper functions, be explicit about defining genders, types, etc. or type a lot of UNKNOWNGENDER, UnknownType, etc. 

Since case classes can have defaults, I think it's a good idea to specify defaults like tpe = UnknownType to make pass writing less annoying and just forcibly run ResolveKinds, ResolveGenders, ResolveTypes, etc. after each transform.

**Comment by azidar** [comment]
Fixed by #460
