### ISSUE TITLE
Remove default "clock" "reset" in Firrtl emission of they aren't used

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/firrtl#472]
I don't want to have dangling ports in the generated Firrtl.

**Comment by aswaterman** [comment]
Isn't that a Chisel problem (hence solved by using RawModule instead of Module)?

**Comment by shunshou** [comment]
Oh does that exist now? Not quite following the discussion.

**Comment by aswaterman** [comment]
I've only heard about it; I hoped you'd know more than me :)

**Comment by azidar** [comment]
This is a chisel issue
