### ISSUE TITLE
Poorly Performing Passes

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/firrtl#49]
Both Lower To Ground and Expand Whens have some performance issues.

My code generates two input Vecs of length N and 1 expected output Vec of length N, the runtime I get is:

N | Lower to Ground (ms) | Expand Whens (ms)
------ | ----- | -----
10 | 9 | 55
100 | 527 | 4496
1000 | 49478 | 425760

Looks like the algorithms are O(n^2)

**Comment by azidar** [comment]
See #113
