### ISSUE TITLE
Change WIR subaccess etc. to expr not exp

### ISSUE THREAD

**Issue by azidar** [ucb-bar/firrtl#521]

**Comment by azidar** [comment]
So the IR nodes SubAccess have a field called expr, but the corresponding field in WSubAccess is exp. So, we just want to be consistent and change the exp -> expr, and fixup all code that references that in the compiler.

**Comment by ucbjrl** [comment]
Got it. Thanks.

**Comment by ucbjrl** [comment]
closed by #586
